In [ ]:
import pandas as pd
import numpy as np 

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv(f'F://datasets//titanic_dataset.csv')

In [4]:
df.head()

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [6]:
df.drop(columns=['class','who','adult_male','deck', 'embark_town', 'alive', 'alone'], inplace=True)

In [7]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [10]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['survived']), 
                                            df['survived'], test_size=0.2, random_state=42)

In [11]:
X_train.head(2)

     pclass   sex   age  sibsp  parch  fare embarked
331       1  male  45.5      0      0  28.5        S
733       2  male  23.0      0      0  13.0        S

In [13]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: survived, dtype: int64

In [14]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [21]:
# appling imputation to age column

si_age = SimpleImputer()
si_embarked = SimpleImputer( strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['age']])
X_train_embarked = si_embarked.fit_transform(X_train[['embarked']]).ravel()

X_test_age = si_age.transform(X_test[['age']])
X_test_embarked = si_embarked.transform(X_test[['embarked']]).ravel()

In [22]:
X_train_embarked

array(['S', 'S', 'S', 'S', 'S', 'C', 'S', 'C', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C',
       'C', 'S', 'S', 'C', 'S', 'C', 'S', 'Q', 'Q', 'S', 'S', 'S', 'C',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'C', 'Q', 'C', 'S', 'S', 'S', 'S', 'C', 'Q', 'S', 'S', 'C', 'S',
       'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'Q', 'C', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'S', 'S',
       'S', 'C', 'S', 'Q', 'S', 'S', 'S', 'S', 'Q', 'C', 'C', 'S', 'S',
       'Q', 'C', 'C', 'S', 'S', 'C', 'S', 'S', 'S', 'C', 'S', 'S', 'S',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'Q', 'S', 'Q', 'C', 'C', 'S', 'S', 'S',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'Q', 'S', 'C', 'S',
       'C', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'Q', 'S', 'S',
       'S', 'Q', 'S', 'C', 'Q', 'S', 'S', 'S', 'S', 'C', 'C', 'Q', 'S',
       'S', 'S', 'S', 'S', 'C', 'C', 'C', 'S', 'S', 'C', 'S', 'S', 'S',
       'C', 'S', 'Q', 'C', 'C', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'Q', 'C', 'S', 'C', 'Q', 'C', 'S', 'S', 'S', 'C', 'S', 'S',
       'C', 'S', 'Q', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'S', 'S', 'C',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S',
       'S', 'S', 'Q', 'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C',
       'Q', 'S', 'S', 'S', 'S', 'C', 'S', 'C', 'Q', 'Q', 'C', 'Q', 'S',
       'C', 'S', 'C', 'S', 'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C',
       'S', 'S', 'C', 'S', 'C', 'C', 'Q', 'S', 'S', 'S', 'S', 'S', 'C',
       'Q', 'S', 'S', 'C', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'Q', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'C', 'S', 'S',
       'Q', 'S', 'S', 'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'Q', 'C', 'S',
       'S', 'S', 'S', 'C', 'S', 'Q', 'C', 'S', 'S', 'S', 'S', 'Q', 'C',
       'S', 'S', 'S', 'S', 'Q', 'Q', 'S', 'C', 'S', 'Q', 'S', 'S', 'S',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'Q', 'S', 'S', 'S', 'S', 'C',
       'C', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'Q', 'S', 'C', 'S', 'S', 'S', 'Q', 'S', 'S', 'S', 'S',
       'S', 'S', 'C', 'C', 'S', 'S', 'S', 'S', 'C', 'C', 'S', 'Q', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'C', 'Q', 'S', 'S', 'C', 'Q', 'S',
       'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'Q',
       'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'C',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'Q', 'C', 'S', 'C',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'C',
       'S', 'S', 'C', 'S', 'C', 'S', 'S', 'S', 'S', 'C', 'S', 'C', 'S',
       'S', 'S', 'Q', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'C',
       'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'Q', 'S', 'S', 'S',
       'S', 'S', 'Q', 'Q', 'S', 'Q', 'Q', 'Q', 'S', 'S', 'S', 'C', 'S',
       'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C',
       'S', 'S', 'C', 'S', 'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'C', 'C', 'C', 'S', 'S',
       'S', 'C', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'Q', 'Q',
       'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'Q', 'S', 'S', 'Q',
       'S', 'S', 'S', 'S', 'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'C', 'C', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'Q', 'Q', 'S',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S'], dtype=object)

In [23]:
ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train[['embarked']])

X_test_sex = ohe_sex.transform(X_test[['sex']])
X_test_embarked = ohe_embarked.transform(X_test[['embarked']])

In [24]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [1]:
X_train.head()

NameError: name 'X_train' is not defined

In [27]:
X_train_rem = X_train.drop(columns=['sex', 'age', 'embarked'])

In [28]:
X_test_rem = X_test.drop(columns=['sex', 'age', 'embarked'])

In [29]:
X_train_transformed = np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transformed = np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

In [30]:
X_test_transformed.shape

(179, 10)

In [31]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [33]:
y_pred = clf.predict(X_test_transformed)
y_pred[:10]

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1])

In [34]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.776536312849162

In [36]:
import pickle

In [37]:
pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))

FileNotFoundError: [Errno 2] No such file or directory: 'models/ohe_sex.pkl'